-include Zpheur/DataTransforms/Dotenv/Env_function.dep
Zpheur/DataTransforms/Dotenv/Env_function.lo: /home/onecthree/Projects/czpheur/Zpheur/DataTransforms/Dotenv/Env_function.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/DataTransforms/Dotenv/Env_function.c -o Zpheur/DataTransforms/Dotenv/Env_function.lo  -MMD -MF Zpheur/DataTransforms/Dotenv/Env_function.dep -MT Zpheur/DataTransforms/Dotenv/Env_function.lo
-include Zpheur/Functions/httpverb_function.dep
Zpheur/Functions/httpverb_function.lo: /home/onecthree/Projects/czpheur/Zpheur/Functions/httpverb_function.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Functions/httpverb_function.c -o Zpheur/Functions/httpverb_function.lo  -MMD -MF Zpheur/Functions/httpverb_function.dep -MT Zpheur/Functions/httpverb_function.lo
-include Zpheur/Functions/is_appns_function.dep
Zpheur/Functions/is_appns_function.lo: /home/onecthree/Projects/czpheur/Zpheur/Functions/is_appns_function.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Functions/is_appns_function.c -o Zpheur/Functions/is_appns_function.lo  -MMD -MF Zpheur/Functions/is_appns_function.dep -MT Zpheur/Functions/is_appns_function.lo
-include Zpheur/Functions/clfile_function.dep
Zpheur/Functions/clfile_function.lo: /home/onecthree/Projects/czpheur/Zpheur/Functions/clfile_function.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Functions/clfile_function.c -o Zpheur/Functions/clfile_function.lo  -MMD -MF Zpheur/Functions/clfile_function.dep -MT Zpheur/Functions/clfile_function.lo
-include Zpheur/Functions/filetoclass_function.dep
Zpheur/Functions/filetoclass_function.lo: /home/onecthree/Projects/czpheur/Zpheur/Functions/filetoclass_function.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Functions/filetoclass_function.c -o Zpheur/Functions/filetoclass_function.lo  -MMD -MF Zpheur/Functions/filetoclass_function.dep -MT Zpheur/Functions/filetoclass_function.lo
-include Zpheur/Functions/zpheur_version_function.dep
Zpheur/Functions/zpheur_version_function.lo: /home/onecthree/Projects/czpheur/Zpheur/Functions/zpheur_version_function.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Functions/zpheur_version_function.c -o Zpheur/Functions/zpheur_version_function.lo  -MMD -MF Zpheur/Functions/zpheur_version_function.dep -MT Zpheur/Functions/zpheur_version_function.lo
-include Zpheur/Actions/Console/DefaultAction_class.dep
Zpheur/Actions/Console/DefaultAction_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Actions/Console/DefaultAction_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Actions/Console/DefaultAction_class.c -o Zpheur/Actions/Console/DefaultAction_class.lo  -MMD -MF Zpheur/Actions/Console/DefaultAction_class.dep -MT Zpheur/Actions/Console/DefaultAction_class.lo
-include Zpheur/Actions/Http/DefaultAction_class.dep
Zpheur/Actions/Http/DefaultAction_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Actions/Http/DefaultAction_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Actions/Http/DefaultAction_class.c -o Zpheur/Actions/Http/DefaultAction_class.lo  -MMD -MF Zpheur/Actions/Http/DefaultAction_class.dep -MT Zpheur/Actions/Http/DefaultAction_class.lo
-include Zpheur/Actions/WebSocket/DefaultAction_class.dep
Zpheur/Actions/WebSocket/DefaultAction_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Actions/WebSocket/DefaultAction_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Actions/WebSocket/DefaultAction_class.c -o Zpheur/Actions/WebSocket/DefaultAction_class.lo  -MMD -MF Zpheur/Actions/WebSocket/DefaultAction_class.dep -MT Zpheur/Actions/WebSocket/DefaultAction_class.lo
-include Zpheur/Actions/Middleware/Next_class.dep
Zpheur/Actions/Middleware/Next_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Actions/Middleware/Next_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Actions/Middleware/Next_class.c -o Zpheur/Actions/Middleware/Next_class.lo  -MMD -MF Zpheur/Actions/Middleware/Next_class.dep -MT Zpheur/Actions/Middleware/Next_class.lo
-include Zpheur/Actions/Middleware_class.dep
Zpheur/Actions/Middleware_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Actions/Middleware_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Actions/Middleware_class.c -o Zpheur/Actions/Middleware_class.lo  -MMD -MF Zpheur/Actions/Middleware_class.dep -MT Zpheur/Actions/Middleware_class.lo
-include Zpheur/Actions/Reflection/ActionResolver_class.dep
Zpheur/Actions/Reflection/ActionResolver_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Actions/Reflection/ActionResolver_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Actions/Reflection/ActionResolver_class.c -o Zpheur/Actions/Reflection/ActionResolver_class.lo  -MMD -MF Zpheur/Actions/Reflection/ActionResolver_class.dep -MT Zpheur/Actions/Reflection/ActionResolver_class.lo
-include Zpheur/Actions/Reflection/ArgumentResolver_class.dep
Zpheur/Actions/Reflection/ArgumentResolver_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Actions/Reflection/ArgumentResolver_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Actions/Reflection/ArgumentResolver_class.c -o Zpheur/Actions/Reflection/ArgumentResolver_class.lo  -MMD -MF Zpheur/Actions/Reflection/ArgumentResolver_class.dep -MT Zpheur/Actions/Reflection/ArgumentResolver_class.lo
-include Zpheur/Caches/Adapter/Filesystem/ItemTagHandler_class.dep
Zpheur/Caches/Adapter/Filesystem/ItemTagHandler_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Caches/Adapter/Filesystem/ItemTagHandler_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Caches/Adapter/Filesystem/ItemTagHandler_class.c -o Zpheur/Caches/Adapter/Filesystem/ItemTagHandler_class.lo  -MMD -MF Zpheur/Caches/Adapter/Filesystem/ItemTagHandler_class.dep -MT Zpheur/Caches/Adapter/Filesystem/ItemTagHandler_class.lo
-include Zpheur/Caches/Adapter/Filesystem_class.dep
Zpheur/Caches/Adapter/Filesystem_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Caches/Adapter/Filesystem_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Caches/Adapter/Filesystem_class.c -o Zpheur/Caches/Adapter/Filesystem_class.lo  -MMD -MF Zpheur/Caches/Adapter/Filesystem_class.dep -MT Zpheur/Caches/Adapter/Filesystem_class.lo
-include Zpheur/Consoles/Input/InputArgument_class.dep
Zpheur/Consoles/Input/InputArgument_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Consoles/Input/InputArgument_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Consoles/Input/InputArgument_class.c -o Zpheur/Consoles/Input/InputArgument_class.lo  -MMD -MF Zpheur/Consoles/Input/InputArgument_class.dep -MT Zpheur/Consoles/Input/InputArgument_class.lo
-include Zpheur/Consoles/Runtime/Application_class.dep
Zpheur/Consoles/Runtime/Application_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Consoles/Runtime/Application_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Consoles/Runtime/Application_class.c -o Zpheur/Consoles/Runtime/Application_class.lo  -MMD -MF Zpheur/Consoles/Runtime/Application_class.dep -MT Zpheur/Consoles/Runtime/Application_class.lo
-include Zpheur/DataTransforms/Dotenv/Dotenv_class.dep
Zpheur/DataTransforms/Dotenv/Dotenv_class.lo: /home/onecthree/Projects/czpheur/Zpheur/DataTransforms/Dotenv/Dotenv_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/DataTransforms/Dotenv/Dotenv_class.c -o Zpheur/DataTransforms/Dotenv/Dotenv_class.lo  -MMD -MF Zpheur/DataTransforms/Dotenv/Dotenv_class.dep -MT Zpheur/DataTransforms/Dotenv/Dotenv_class.lo
-include Zpheur/Dependencies/ServiceLocator/Container_class.dep
Zpheur/Dependencies/ServiceLocator/Container_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Dependencies/ServiceLocator/Container_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Dependencies/ServiceLocator/Container_class.c -o Zpheur/Dependencies/ServiceLocator/Container_class.lo  -MMD -MF Zpheur/Dependencies/ServiceLocator/Container_class.dep -MT Zpheur/Dependencies/ServiceLocator/Container_class.lo
-include Zpheur/Schemes/Http/Foundation/ParameterBag_class.dep
Zpheur/Schemes/Http/Foundation/ParameterBag_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Foundation/ParameterBag_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Foundation/ParameterBag_class.c -o Zpheur/Schemes/Http/Foundation/ParameterBag_class.lo  -MMD -MF Zpheur/Schemes/Http/Foundation/ParameterBag_class.dep -MT Zpheur/Schemes/Http/Foundation/ParameterBag_class.lo
-include Zpheur/Schemes/Http/Foundation/HeaderBag_class.dep
Zpheur/Schemes/Http/Foundation/HeaderBag_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Foundation/HeaderBag_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Foundation/HeaderBag_class.c -o Zpheur/Schemes/Http/Foundation/HeaderBag_class.lo  -MMD -MF Zpheur/Schemes/Http/Foundation/HeaderBag_class.dep -MT Zpheur/Schemes/Http/Foundation/HeaderBag_class.lo
-include Zpheur/Schemes/Http/Foundation/InputBag_class.dep
Zpheur/Schemes/Http/Foundation/InputBag_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Foundation/InputBag_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Foundation/InputBag_class.c -o Zpheur/Schemes/Http/Foundation/InputBag_class.lo  -MMD -MF Zpheur/Schemes/Http/Foundation/InputBag_class.dep -MT Zpheur/Schemes/Http/Foundation/InputBag_class.lo
-include Zpheur/Schemes/Http/Foundation/Kernel_class.dep
Zpheur/Schemes/Http/Foundation/Kernel_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Foundation/Kernel_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Foundation/Kernel_class.c -o Zpheur/Schemes/Http/Foundation/Kernel_class.lo  -MMD -MF Zpheur/Schemes/Http/Foundation/Kernel_class.dep -MT Zpheur/Schemes/Http/Foundation/Kernel_class.lo
-include Zpheur/Schemes/Http/Foundation/Request_class.dep
Zpheur/Schemes/Http/Foundation/Request_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Foundation/Request_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Foundation/Request_class.c -o Zpheur/Schemes/Http/Foundation/Request_class.lo  -MMD -MF Zpheur/Schemes/Http/Foundation/Request_class.dep -MT Zpheur/Schemes/Http/Foundation/Request_class.lo
-include Zpheur/Schemes/Http/Foundation/ServerBag_class.dep
Zpheur/Schemes/Http/Foundation/ServerBag_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Foundation/ServerBag_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Foundation/ServerBag_class.c -o Zpheur/Schemes/Http/Foundation/ServerBag_class.lo  -MMD -MF Zpheur/Schemes/Http/Foundation/ServerBag_class.dep -MT Zpheur/Schemes/Http/Foundation/ServerBag_class.lo
-include Zpheur/Schemes/Http/Message/HeaderInterface_class.dep
Zpheur/Schemes/Http/Message/HeaderInterface_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Message/HeaderInterface_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Message/HeaderInterface_class.c -o Zpheur/Schemes/Http/Message/HeaderInterface_class.lo  -MMD -MF Zpheur/Schemes/Http/Message/HeaderInterface_class.dep -MT Zpheur/Schemes/Http/Message/HeaderInterface_class.lo
-include Zpheur/Schemes/Http/Message/HeaderTrait_class.dep
Zpheur/Schemes/Http/Message/HeaderTrait_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Message/HeaderTrait_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Message/HeaderTrait_class.c -o Zpheur/Schemes/Http/Message/HeaderTrait_class.lo  -MMD -MF Zpheur/Schemes/Http/Message/HeaderTrait_class.dep -MT Zpheur/Schemes/Http/Message/HeaderTrait_class.lo
-include Zpheur/Schemes/Http/Message/Response_class.dep
Zpheur/Schemes/Http/Message/Response_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Message/Response_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Message/Response_class.c -o Zpheur/Schemes/Http/Message/Response_class.lo  -MMD -MF Zpheur/Schemes/Http/Message/Response_class.dep -MT Zpheur/Schemes/Http/Message/Response_class.lo
-include Zpheur/Schemes/Http/Responder/ErrorRequest_class.dep
Zpheur/Schemes/Http/Responder/ErrorRequest_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Responder/ErrorRequest_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Responder/ErrorRequest_class.c -o Zpheur/Schemes/Http/Responder/ErrorRequest_class.lo  -MMD -MF Zpheur/Schemes/Http/Responder/ErrorRequest_class.dep -MT Zpheur/Schemes/Http/Responder/ErrorRequest_class.lo
-include Zpheur/Schemes/Http/Routing/Dispatcher/DispatchItem_class.dep
Zpheur/Schemes/Http/Routing/Dispatcher/DispatchItem_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Routing/Dispatcher/DispatchItem_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Routing/Dispatcher/DispatchItem_class.c -o Zpheur/Schemes/Http/Routing/Dispatcher/DispatchItem_class.lo  -MMD -MF Zpheur/Schemes/Http/Routing/Dispatcher/DispatchItem_class.dep -MT Zpheur/Schemes/Http/Routing/Dispatcher/DispatchItem_class.lo
-include Zpheur/Schemes/Http/Routing/Dispatcher_class.dep
Zpheur/Schemes/Http/Routing/Dispatcher_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Routing/Dispatcher_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Routing/Dispatcher_class.c -o Zpheur/Schemes/Http/Routing/Dispatcher_class.lo  -MMD -MF Zpheur/Schemes/Http/Routing/Dispatcher_class.dep -MT Zpheur/Schemes/Http/Routing/Dispatcher_class.lo
-include Zpheur/Schemes/Http/Routing/Route_class.dep
Zpheur/Schemes/Http/Routing/Route_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Routing/Route_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Schemes/Http/Routing/Route_class.c -o Zpheur/Schemes/Http/Routing/Route_class.lo  -MMD -MF Zpheur/Schemes/Http/Routing/Route_class.dep -MT Zpheur/Schemes/Http/Routing/Route_class.lo
-include Zpheur/Files/Mime_class.dep
Zpheur/Files/Mime_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Files/Mime_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Files/Mime_class.c -o Zpheur/Files/Mime_class.lo  -MMD -MF Zpheur/Files/Mime_class.dep -MT Zpheur/Files/Mime_class.lo
-include Zpheur/Databases/Voile_class.dep
Zpheur/Databases/Voile_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Databases/Voile_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Databases/Voile_class.c -o Zpheur/Databases/Voile_class.lo  -MMD -MF Zpheur/Databases/Voile_class.dep -MT Zpheur/Databases/Voile_class.lo
-include Zpheur/Databases/Voile/Model_class.dep
Zpheur/Databases/Voile/Model_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Databases/Voile/Model_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Databases/Voile/Model_class.c -o Zpheur/Databases/Voile/Model_class.lo  -MMD -MF Zpheur/Databases/Voile/Model_class.dep -MT Zpheur/Databases/Voile/Model_class.lo
-include Zpheur/Databases/Voile/Collection_class.dep
Zpheur/Databases/Voile/Collection_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Databases/Voile/Collection_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Databases/Voile/Collection_class.c -o Zpheur/Databases/Voile/Collection_class.lo  -MMD -MF Zpheur/Databases/Voile/Collection_class.dep -MT Zpheur/Databases/Voile/Collection_class.lo
-include Zpheur/Databases/Voile/Schema/Attributes_class.dep
Zpheur/Databases/Voile/Schema/Attributes_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Databases/Voile/Schema/Attributes_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Databases/Voile/Schema/Attributes_class.c -o Zpheur/Databases/Voile/Schema/Attributes_class.lo  -MMD -MF Zpheur/Databases/Voile/Schema/Attributes_class.dep -MT Zpheur/Databases/Voile/Schema/Attributes_class.lo
-include Zpheur/Databases/Voile/Schema/AbstractionType_class.dep
Zpheur/Databases/Voile/Schema/AbstractionType_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Databases/Voile/Schema/AbstractionType_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Databases/Voile/Schema/AbstractionType_class.c -o Zpheur/Databases/Voile/Schema/AbstractionType_class.lo  -MMD -MF Zpheur/Databases/Voile/Schema/AbstractionType_class.dep -MT Zpheur/Databases/Voile/Schema/AbstractionType_class.lo
-include Zpheur/Databases/Phase_class.dep
Zpheur/Databases/Phase_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Databases/Phase_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Databases/Phase_class.c -o Zpheur/Databases/Phase_class.lo  -MMD -MF Zpheur/Databases/Phase_class.dep -MT Zpheur/Databases/Phase_class.lo
-include Zpheur/Databases/Phase/Model_class.dep
Zpheur/Databases/Phase/Model_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Databases/Phase/Model_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Databases/Phase/Model_class.c -o Zpheur/Databases/Phase/Model_class.lo  -MMD -MF Zpheur/Databases/Phase/Model_class.dep -MT Zpheur/Databases/Phase/Model_class.lo
-include Zpheur/Databases/Phase/Schema/AbstractionType_class.dep
Zpheur/Databases/Phase/Schema/AbstractionType_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Databases/Phase/Schema/AbstractionType_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Databases/Phase/Schema/AbstractionType_class.c -o Zpheur/Databases/Phase/Schema/AbstractionType_class.lo  -MMD -MF Zpheur/Databases/Phase/Schema/AbstractionType_class.dep -MT Zpheur/Databases/Phase/Schema/AbstractionType_class.lo
-include Zpheur/Databases/Phase/Schema/Attributes_class.dep
Zpheur/Databases/Phase/Schema/Attributes_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Databases/Phase/Schema/Attributes_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Databases/Phase/Schema/Attributes_class.c -o Zpheur/Databases/Phase/Schema/Attributes_class.lo  -MMD -MF Zpheur/Databases/Phase/Schema/Attributes_class.dep -MT Zpheur/Databases/Phase/Schema/Attributes_class.lo
-include Zpheur/Logs/StreamLog_class.dep
Zpheur/Logs/StreamLog_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Logs/StreamLog_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Logs/StreamLog_class.c -o Zpheur/Logs/StreamLog_class.lo  -MMD -MF Zpheur/Logs/StreamLog_class.dep -MT Zpheur/Logs/StreamLog_class.lo
-include Zpheur/Logs/StreamLog/StreamHandler_class.dep
Zpheur/Logs/StreamLog/StreamHandler_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Logs/StreamLog/StreamHandler_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Logs/StreamLog/StreamHandler_class.c -o Zpheur/Logs/StreamLog/StreamHandler_class.lo  -MMD -MF Zpheur/Logs/StreamLog/StreamHandler_class.dep -MT Zpheur/Logs/StreamLog/StreamHandler_class.lo
-include Zpheur/Logs/StreamLog/Level_class.dep
Zpheur/Logs/StreamLog/Level_class.lo: /home/onecthree/Projects/czpheur/Zpheur/Logs/StreamLog/Level_class.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Logs/StreamLog/Level_class.c -o Zpheur/Logs/StreamLog/Level_class.lo  -MMD -MF Zpheur/Logs/StreamLog/Level_class.dep -MT Zpheur/Logs/StreamLog/Level_class.lo
-include Zpheur/Strings/contains_function.dep
Zpheur/Strings/contains_function.lo: /home/onecthree/Projects/czpheur/Zpheur/Strings/contains_function.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Strings/contains_function.c -o Zpheur/Strings/contains_function.lo  -MMD -MF Zpheur/Strings/contains_function.dep -MT Zpheur/Strings/contains_function.lo
-include Zpheur/Encryptions/Random/Generator/csrf_token_function.dep
Zpheur/Encryptions/Random/Generator/csrf_token_function.lo: /home/onecthree/Projects/czpheur/Zpheur/Encryptions/Random/Generator/csrf_token_function.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/Zpheur/Encryptions/Random/Generator/csrf_token_function.c -o Zpheur/Encryptions/Random/Generator/csrf_token_function.lo  -MMD -MF Zpheur/Encryptions/Random/Generator/csrf_token_function.dep -MT Zpheur/Encryptions/Random/Generator/csrf_token_function.lo
-include include/libstr.dep
include/libstr.lo: /home/onecthree/Projects/czpheur/include/libstr.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/include/libstr.c -o include/libstr.lo  -MMD -MF include/libstr.dep -MT include/libstr.lo
-include include/onecstr.dep
include/onecstr.lo: /home/onecthree/Projects/czpheur/include/onecstr.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/include/onecstr.c -o include/onecstr.lo  -MMD -MF include/onecstr.dep -MT include/onecstr.lo
-include include/runtime.dep
include/runtime.lo: /home/onecthree/Projects/czpheur/include/runtime.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/include/runtime.c -o include/runtime.lo  -MMD -MF include/runtime.dep -MT include/runtime.lo
-include include/regexp.dep
include/regexp.lo: /home/onecthree/Projects/czpheur/include/regexp.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/include/regexp.c -o include/regexp.lo  -MMD -MF include/regexp.dep -MT include/regexp.lo
-include include/dotenv.dep
include/dotenv.lo: /home/onecthree/Projects/czpheur/include/dotenv.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/include/dotenv.c -o include/dotenv.lo  -MMD -MF include/dotenv.dep -MT include/dotenv.lo
-include include/furouter.dep
include/furouter.lo: /home/onecthree/Projects/czpheur/include/furouter.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/include/furouter.c -o include/furouter.lo  -MMD -MF include/furouter.dep -MT include/furouter.lo
-include include/zerror.dep
include/zerror.lo: /home/onecthree/Projects/czpheur/include/zerror.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/include/zerror.c -o include/zerror.lo  -MMD -MF include/zerror.dep -MT include/zerror.lo
-include zpheur_hem.dep
zpheur_hem.lo: /home/onecthree/Projects/czpheur/zpheur_hem.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/zpheur_hem.c -o zpheur_hem.lo  -MMD -MF zpheur_hem.dep -MT zpheur_hem.lo
-include zpheur.dep
zpheur.lo: /home/onecthree/Projects/czpheur/zpheur.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/home/onecthree/Projects/czpheur $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)    -fcommon -lpcre2-8 -DZPHEUR_REQUIRE_VOILE -DZEND_COMPILE_DL_EXT=1 -c /home/onecthree/Projects/czpheur/zpheur.c -o zpheur.lo  -MMD -MF zpheur.dep -MT zpheur.lo
$(phplibdir)/zpheur.la: ./zpheur.la
	$(LIBTOOL) --tag=CC --mode=install cp ./zpheur.la $(phplibdir)

./zpheur.la: $(shared_objects_zpheur) $(ZPHEUR_SHARED_DEPENDENCIES)
	$(LIBTOOL) --tag=CC --mode=link $(CC) -shared $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_zpheur) $(ZPHEUR_SHARED_LIBADD)

