
#ifndef H_ZPHEUR_ENCRYPTIONS_RANDOM_GENERATOR_CSRF_TOKEN
#define H_ZPHEUR_ENCRYPTIONS_RANDOM_GENERATOR_CSRF_TOKEN


ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(csrf_token_arginfo, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, prefix, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, writeToFile, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

#endif