
#ifndef H_ZPHEUR_FUNCTIONS_CLFILE
#define H_ZPHEUR_FUNCTIONS_CLFILE

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_clfile, 0, 1, IS_STRING, 0)
    ZEND_ARG_TYPE_INFO(0, class_name, IS_STRING, 0)
ZEND_END_ARG_INFO()

#endif