
#ifndef H_ZPHEUR_FUNCTIONS_FILETOCLASS
#define H_ZPHEUR_FUNCTIONS_FILETOCLASS

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(filetoclass_arginfo, 0, 1, IS_STRING, 0)
    ZEND_ARG_TYPE_INFO(0, filename, IS_STRING, 0)
ZEND_END_ARG_INFO()

#endif