
#ifndef H_ZPHEUR_FUNCTIONS_IS_APPNS
#define H_ZPHEUR_FUNCTIONS_IS_APPNS

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(is_appns_arginfo, 0, 1, _IS_BOOL, 0)
    ZEND_ARG_TYPE_INFO(0, class_name, IS_STRING, 0)
ZEND_END_ARG_INFO()

#endif