
#ifndef H_ZPHEUR_FUNCTIONS_ZPHEUR_VERSION
#define H_ZPHEUR_FUNCTIONS_ZPHEUR_VERSION

#define _Z_ONLY_TAG		1 << 1
#define _Z_ONLY_NUMBER  1 << 2

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(zpheur_version_arginfo, 0, 1, IS_STRING, 0)
ZEND_END_ARG_INFO()

#endif