
#ifndef H_ZPHEUR_RANDOMIZES_RANDOM_CHARS
#define H_ZPHEUR_RANDOMIZES_RANDOM_CHARS

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(random_chars_arginfo, 0, 2, IS_STRING | IS_FALSE, 0)
    ZEND_ARG_TYPE_INFO(0, chars_set, IS_STRING, 0)
    ZEND_ARG_TYPE_INFO(0, random_length, IS_STRING, 0)
ZEND_END_ARG_INFO()

#endif