
#ifndef H_ZPHEUR_STRINGS_CONTAINS
#define H_ZPHEUR_STRINGS_CONTAINS

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(contains_arginfo, 0, 1, _IS_BOOL, 0)
    ZEND_ARG_TYPE_INFO(0, needle, IS_STRING, 0)
ZEND_END_ARG_INFO()

#endif